services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - .:/tabbik-backend
      - /tabbik-backend/node_modules
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    command: -p ${PGPORT}

  redis:
    container_name: redis_container
    image: "redis:7.4.0-alpine"
    ports:
      - "6379:6379"

volumes:
  db_data:
